"""初期テーブルの作成

【概要】
app_user・equipment・loan_request・notificationの各テーブルと、制約・インデックスを作成する。
作成時点のDDLを固定した内容とする（今後のモデル変更は、本ファイルを変更せず差分マイグレーションで行う）。
二重貸出防止の排他制約にbtree_gist拡張が必要なため、最初に有効化する。

設計書：設計書/テーブル定義（models）

Revision ID: 0001
Revises:
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """拡張機能を有効化し、全テーブルを作成する"""
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('login_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=50), server_default='', nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), server_default='general', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('token_generation', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("login_id ~ '^[A-Za-z0-9_-]+$'", name='ck_app_user_login_id_format'),
    sa.CheckConstraint("role IN ('general', 'admin')", name='ck_app_user_role'),
    sa.CheckConstraint('failed_login_count >= 0', name='ck_app_user_failed_login_count'),
    sa.CheckConstraint('token_generation >= 0', name='ck_app_user_token_generation'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('asset_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), server_default='', nullable=False),
    sa.Column('location', sa.String(length=100), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_number ~ '^[A-Za-z0-9-]+$'", name='ck_equipment_asset_number_format'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_number')
    )
    op.create_index(op.f('ix_equipment_category'), 'equipment', ['category'], unique=False)
    op.create_table('loan_request',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='requested', nullable=False),
    sa.Column('reason', sa.String(length=200), server_default='', nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('lent_by', sa.Integer(), nullable=True),
    sa.Column('returned_by', sa.Integer(), nullable=True),
    sa.Column('canceled_by', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_note', sa.String(length=200), server_default='', nullable=False),
    postgresql.ExcludeConstraint((sa.column('equipment_id'), '='), (sa.text("daterange(start_date, due_date, '[]')"), '&&'), where=sa.text("status IN ('approved', 'lent')"), using='gist', name='ex_loan_request_equipment_period'),
    sa.CheckConstraint("status IN ('requested', 'approved', 'lent', 'returned', 'rejected', 'canceled')", name='ck_loan_request_status'),
    sa.CheckConstraint('due_date >= start_date', name='ck_loan_request_period'),
    sa.ForeignKeyConstraint(['canceled_by'], ['app_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decided_by'], ['app_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lent_by'], ['app_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_id'], ['app_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['returned_by'], ['app_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_request_equipment_id'), 'loan_request', ['equipment_id'], unique=False)
    op.create_index('ix_loan_request_equipment_status', 'loan_request', ['equipment_id', 'status'], unique=False)
    op.create_index('ix_loan_request_requester', 'loan_request', ['requester_id', 'requested_at'], unique=False)
    op.create_index(op.f('ix_loan_request_requester_id'), 'loan_request', ['requester_id'], unique=False)
    op.create_index(op.f('ix_loan_request_status'), 'loan_request', ['status'], unique=False)
    op.create_index('ix_loan_request_status_due', 'loan_request', ['status', 'due_date'], unique=False)
    op.create_index('uq_loan_request_equipment_lent', 'loan_request', ['equipment_id'], unique=True, postgresql_where=sa.text("status = 'lent'"))
    op.create_table('notification',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('loan_request_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notified_date', sa.Date(), nullable=False),
    sa.CheckConstraint("type IN ('approved', 'rejected', 'canceled', 'new_request', 'due_soon', 'overdue')", name='ck_notification_type'),
    sa.ForeignKeyConstraint(['loan_request_id'], ['loan_request.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_id'], ['app_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_loan_request_id'), 'notification', ['loan_request_id'], unique=False)
    op.create_index('ix_notification_recipient_read_created', 'notification', ['recipient_id', 'is_read', 'created_at'], unique=False)
    op.create_index('uq_notification_daily', 'notification', ['recipient_id', 'type', 'loan_request_id', 'notified_date'], unique=True, postgresql_where=sa.text("type IN ('due_soon', 'overdue')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """全テーブルを削除する（拡張機能は他の用途の可能性があるため残す）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notification_daily', table_name='notification', postgresql_where=sa.text("type IN ('due_soon', 'overdue')"))
    op.drop_index('ix_notification_recipient_read_created', table_name='notification')
    op.drop_index(op.f('ix_notification_loan_request_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index('uq_loan_request_equipment_lent', table_name='loan_request', postgresql_where=sa.text("status = 'lent'"))
    op.drop_index('ix_loan_request_status_due', table_name='loan_request')
    op.drop_index(op.f('ix_loan_request_status'), table_name='loan_request')
    op.drop_index(op.f('ix_loan_request_requester_id'), table_name='loan_request')
    op.drop_index('ix_loan_request_requester', table_name='loan_request')
    op.drop_index('ix_loan_request_equipment_status', table_name='loan_request')
    op.drop_index(op.f('ix_loan_request_equipment_id'), table_name='loan_request')
    op.drop_table('loan_request')
    op.drop_index(op.f('ix_equipment_category'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_table('app_user')
    # ### end Alembic commands ###
